services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/database_schema/postgres:/docker-entrypoint-initdb.d

  timescale:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/database_schema/timescale:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    depends_on:
      postgres:
        condition: service_healthy
      timescale:
        condition: service_healthy
    environment:
      PORT: 8080
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_ADDRESS: postgres
      DATABASE_NAME: postgres
      GIN_MODE: release
    restart: always
    ports:
      - 127.0.0.1:8080:8080

  data-fetcher:
    build:
      context: ./backend
      dockerfile: Dockerfile.data-fetcher
    depends_on:
      postgres:
        condition: service_healthy
      timescale:
        condition: service_healthy
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_ADDRESS: postgres
      DATABASE_NAME: postgres
      TIMESCALE_USERNAME: postgres
      TIMESCALE_PASSWORD: password
      TIMESCALE_ADDRESS: timescale
      TIMESCALE_NAME: postgres
      VELIB_API_STATIONS_URL: https://velib-metropole-opendata.smovengo.cloud/opendata/Velib_Metropole/station_information.json
      VELIB_API_STATUSES_URL: https://velib-metropole-opendata.smovengo.cloud/opendata/Velib_Metropole/station_status.json
    restart: always

  webapp:
    build:
      context: ./webapp
    depends_on:
      - api
    ports:
      - 127.0.0.1:3000:80