services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
    restart: always
    ports:
      - 8080:8080