services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./database_schema:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_ADDRESS: postgres
      DATABASE_NAME: postgres
    restart: always
    ports:
      - 8080:8080