services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "127.0.0.1:16686:16686"

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/database_schema/postgres:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:5432:5432

  fetcher:
    build:
      context: ./backend
      dockerfile: ./cmd/fetcher/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_ADDRESS: postgres
      DATABASE_NAME: postgres
      VELIB_API_STATIONS_URL: https://velib-metropole-opendata.smovengo.cloud/opendata/Velib_Metropole/station_information.json
      VELIB_API_STATUSES_URL: https://velib-metropole-opendata.smovengo.cloud/opendata/Velib_Metropole/station_status.json
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    restart: always

  api:
    build:
      context: ./backend
      dockerfile: ./cmd/api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_ADDRESS: postgres
      DATABASE_NAME: postgres
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    restart: always
    ports:
      - 127.0.0.1:8080:8080

  webapp:
    build:
      context: ./webapp
    depends_on:
      - api
    ports:
      - 127.0.0.1:3000:80